#!/usr/bin/env bash
# docker/setup.sh — Auto-detect SICStus Prolog and write .env
# Run once before `docker compose up --build`.
# Usage: bash docker/setup.sh  (from f1_race/ directory)
set -euo pipefail

ENV_FILE="$(dirname "$0")/../.env"
EXAMPLE_FILE="$(dirname "$0")/../.env.example"

# ── 1. Detect SICStus path ────────────────────────────────────────────────────
detect_sicstus() {
    # Priority order:
    # 1. Standard install path (most common on Linux/WSL)
    if   [ -x "/usr/local/sicstus4.6.0/bin/sicstus" ]; then
        echo "/usr/local/sicstus4.6.0"
    # 2. In PATH (e.g. /opt/sicstus4.6.0 or custom prefix)
    elif command -v sicstus &>/dev/null; then
        # sicstus lives in <prefix>/bin/sicstus → strip /bin/sicstus
        dirname "$(dirname "$(command -v sicstus)")"
    # 3. Common alternate prefixes
    elif [ -x "/opt/sicstus4.6.0/bin/sicstus" ]; then
        echo "/opt/sicstus4.6.0"
    else
        echo ""
    fi
}

DETECTED=$(detect_sicstus)

# ── 2. Prompt user ────────────────────────────────────────────────────────────
if [ -n "$DETECTED" ]; then
    echo "SICStus Prolog detected at: $DETECTED"
    read -r -p "Use this path? [Y/n]: " CONFIRM
    CONFIRM="${CONFIRM:-Y}"
    if [[ "$CONFIRM" =~ ^[Nn] ]]; then
        read -r -p "Enter SICStus path manually: " DETECTED
    fi
else
    echo "SICStus Prolog NOT found automatically."
    read -r -p "Enter the full path to your SICStus install (e.g. /usr/local/sicstus4.6.0): " DETECTED
fi

if [ -z "$DETECTED" ] || [ ! -x "$DETECTED/bin/sicstus" ]; then
    echo "ERROR: '$DETECTED/bin/sicstus' not found or not executable." >&2
    exit 1
fi

# ── 3. Write .env ─────────────────────────────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# Auto-generated by docker/setup.sh — $(date)
# Edit SICSTUS_PATH if you move your SICStus installation.

SICSTUS_PATH=$DETECTED
EOF

echo ""
echo ".env written:"
cat "$ENV_FILE"
echo ""
echo "You can now run:  docker compose up --build -d"
